### PR TITLE
Fixnum deprecation fix

### PR DESCRIPTION
**Pull request by dmkl**

### CODE REVIEW

**Comment by syntaxTerr0r** [comment]
Any news on this?
The PR is backward compatible with previous Ruby version since Fixnum inherit from Integer and fixes deprecation warning in Ruby 2.4 and above.

**Comment by archan937** [comment]
Sorry for the (very) late reply, guys

**Comment by syntaxTerr0r** [comment]
Thanks @archan937! To fix the CI you just need to remove this:
```
- rbx-18mode
- rbx-19mode
```
from `.travis.yml` and replace it with : 
```
- rbx-2
```
Could be nice to add `2.5.0` too.

**Comment by archan937** [comment]
Done

**Comment by dmkl** [comment]
@archan937 could you release a new gem version, please?

**Comment by archan937** [comment]
Done https://rubygems.org/gems/slot_machine/versions/0.1.2

**Pull request merged**
